trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Dev
  jobs:
  - job: BuildAndDeployDev
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'MyAzureSubscription'
        appName: 'MyAppServiceDev'
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'

- stage: Prod
  condition: succeeded()
  jobs:
  - job: BuildAndDeployProd
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'MyAzureSubscription'
        appName: 'MyAppServiceProd'
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
